apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: petstore
  name: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petstore
    spec:
      containers:
      - image: swaggerapi/petstore3
        name: petstore3
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: petstore
  name: petstore
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: petstore
status:
  loadBalancer: {}
