# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: kusk-gateway-test    # Add your cluster name here.
  GKE_ZONE: us-east1-c   # Add your cluster zone here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        service_account: 'kgw-deployer@kusk-330514.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: 'fetch kgw'
      run: |-
        curl -sSLf https://github.com/kubeshop/kgw/releases/download/v0.1.1/kgw_0.1.1_Linux_x86_64.tar.gz > kgw.tar.gz
        tar -xzf kgw.tar.gz kgw
        rm kgw.tar.gz
        mv kgw /usr/local/bin/kgw
    
    - name: 'run kgw'
      run: |-
        kgw api generate -i api/swagger.yaml | kubectl apply -f -
     